/** Semantic icon names → Unicons ids (Iconify `uil:*`). */
export const AppIcons = {
  home: 'home',
  airplane: 'plane',
  network: 'users-alt',
  events: 'calendar',
  messages: 'comment-alt-dots',
  send: 'location-arrow',
  friends: 'heart',
  profile: 'user-circle',
  email: 'envelope',
  upload: 'upload',
  settings: 'setting',
  shield: 'shield-check',
  signOut: 'signout',
  edit: 'edit',
  privacy: 'eye-slash',
  roster: 'file-alt',
  verified: 'shield-check',
  pending: 'clock',
  chevronRight: 'arrow-right',
  chevronDown: 'angle-down',
  chevronLeft: 'angle-left',
  checkboxOn: 'check-square',
  checkboxOff: 'square-full',
  bell: 'bell',
  camera: 'camera',
  phone: 'phone',
  menu: 'bars',
  add: 'plus-circle',
  copy: 'copy',
  check: 'check',
  share: 'share',
  search: 'search',
  userPlus: 'user-plus',
  mapPoint: 'map-marker',
  globe: 'globe',
  lock: 'lock',
  sun: 'sun',
  moon: 'moon',
  genderMale: 'mars',
  genderFemale: 'venus',
} as const;

export type AppIconName = keyof typeof AppIcons;

export type UniconsIconId = (typeof AppIcons)[AppIconName];
